run_name: "NA"
epochs: 100
device: 0
seed: 2023
log_dir: "./"

dataset:
  data_dir: "../../data/MSP/"
  recompute: False
  big_graphs: True
  use_xyz: False

loader:
  batch_size_train: 20
  batch_size_val: 20
  num_workers: 2
  pin_memory: False
  prefetch_factor: 2
  shuffle: True

model:
  in_channels: 19
  out_channel: 64
  C_width: 96
  N_block: 3
  drate: 0.3
  batch_norm: True
  use_max: True
  use_mean: False
  pos_weight: 4
  use_graph: False
  use_graph_only: False
  graph_model: 'parallel'
  use_gat: False
  use_v2: False
  use_mp: False
  use_skip: False
  neigh_th: 8
  flash: True
  output_graph: True
  use_distance: False

optimizer:
  lr: 1e-4
  patience: 100
  factor: 0.5

train:
  save_top_k: 2
  early_stoping_patience: 100
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  overfit_batches: 0.0
  gradient_clip_val: 1.0
  deterministic: False


hydra:
  run:
    dir: ../../outputs/msp/
