run_name: "NA"
epochs: 100
device: 0
seed: 2023
log_dir: "./"
path_model: version_xxx/checkpoints/last.ckpt

dataset:
  data_dir: "../../data/PIP/DIPS-split/data/"
  neg_to_pos_ratio: 1
  max_pos_regions_per_ensemble: 5
  recompute: False
  big_graphs: True
  use_xyz: False

loader:
  batch_size_train: 16
  batch_size_val: 16
  num_workers: 4
  pin_memory: False
  prefetch_factor: 2
  shuffle: True

model:
  in_channels: 19
  out_channel: 64
  C_width: 96
  N_block: 3
  dropout: 0.3
  batch_norm: True
  sigma: 2.5
  pos_weight: 4
  use_graph: False
  use_graph_only: False
  graph_model: 'parallel'
  use_gat: False
  clip_output: False
  output_graph: True

optimizer:
  lr: 1e-4
  patience: 100
  factor: 0.5

train:
  save_top_k: 2
  early_stoping_patience: 20
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  overfit_batches: 0.0
  gradient_clip_val: 1.0
  deterministic: False


hydra:
  run:
    dir: ../../outputs/pip/
