run_name: "NA"
epochs: 100
device: 1
seed: 2023
log_dir: "./"

dataset:
  data_dir: "../../data/PSR/"
  recompute: False

loader:
  batch_size_train: 1
  batch_size_val: 1
  num_workers: 6
  pin_memory: False

model:
  in_channels: 5
  out_channel: 64
  C_width: 96
  N_block: 3
  dropout: 0.3
  batch_norm: False

optimizer:
  lr: 1e-3

train:
  save_top_k: 2
  early_stoping_patience: 10
  accumulate_grad_batches: 8
  val_check_interval: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  overfit_batches: 0.0
  gradient_clip_val: 1.0


hydra:
  run:
    dir: ../outputs/psr/
