run_name: "NA"
epochs: 100
device: 0
seed: 2023
log_dir: "./"
path_model: "version_x/checkpoints/last.ckpt"

dataset:
  data_dir: "../../data/masif_site/"

loader:
  batch_size_train: 16
  batch_size_val: 16
  num_workers: 4
  pin_memory: False
  prefetch_factor: 2
  shuffle: True

model:
  in_channels: 37
  in_channels_surf: 25
  out_channel: 64
  C_width: 96
  N_block: 3
  dropout: 0.3
  use_mean: False
  batch_norm: True
  graph_model: 'bipartite'
  use_gat: False
  use_v2: False
  use_skip: False
  neigh_th: 8
  use_distance: False
  add_seq_emb: False

optimizer:
  lr: 1e-4
  patience: 100
  factor: 0.5

train:
  save_top_k: 2
  early_stoping_patience: 100
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  overfit_batches: 0.0
  gradient_clip_val: 1.0
  deterministic: False


hydra:
  run:
    dir: ../../outputs/masif_site/
