epochs: 100
device: 0
seed: 2023
log_dir: "./logs"

dataset:
  data_dir: "../data/PIP/DIPS-split/data/"
  neg_to_pos_ratio: 1
  max_pos_regions_per_ensemble: 5
  recompute: False

loader:
  batch_size_train: 1
  batch_size_val: 1
  num_workers: 6

model:
  in_channels: 5
  out_channel: 64
  dropout: 0.3
  batch_norm: False