defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  job:
    chdir: False

# logging
run_name: default
out_dir: ../../data/MasifLigand/out_dir
test_freq: 5
seed: 2023
auto_resume: False
mute_tqdm: False

# data args
data_dir: ../../data/MasifLigand2/dataset_MasifLigand/
processed_dir: ../../data/MasifLigand2/cache_npz
operator_dir: ../../data/MasifLigand2/cache_operator
train_split_file: splits/train-list.txt
valid_split_file: splits/val-list.txt
test_split_file: splits/test-list.txt
use_chem_feat: True
skip_hydro: False
use_geom_feat: True
max_eigen_val: 5.0
num_signatures: 16
smoothing: False
use_distance: False

# loader args
batch_size: 16
num_data_workers: 4
num_gdf: 16

# model args
model_name: psr
c_width: 150
n_blocks: 6
in_channels_surf: 54
with_gradient_features: True
dropout: 0.5
use_v2: False
batch_norm: True
use_pesto: False
pesto_width: 16
use_graph: True
use_graph_only: False
neigh_th: 8
use_ema: False
ema_decay: 0.995
ema_update_every: 10

# optimizer arguments
optimizer: Adam
epochs: 400
warmup_epochs: 10
lr: 0.0005
lr_scheduler: CosineAnnealingLRWithWarmup  # PolynomialLRWithWarmup, CosineAnnealingLRWithWarmup constant
lr_eta_min: 1E-8
weight_decay: 0
clip_grad_norm: 1.0
fp16: False
shrink_outputs: 0.
shrink_epochs: 30

# model-specific arguments
device: -1