defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  job:
    chdir: False

# logging
run_name: default
out_dir: ../../data/MasifLigand/out_dir
test_freq: 10
seed: 2023
auto_resume: False
mute_tqdm: False

# data args
data_dir: ../../data/MasifLigand/dataset_MasifLigand/
processed_dir: ../../data/MasifLigand/cache_npz
operator_dir: ../../data/MasifLigand/cache_operator
train_split_file: splits/train-list.txt
valid_split_file: splits/val-list.txt
test_split_file: splits/test-list.txt
use_chem_feat: True
skip_hydro: False
use_geom_feat: True
max_eigen_val: 5.0
num_signatures: 16
smoothing: False

# loader args
batch_size: 16
num_data_workers: 4
num_gdf: 16

# model args
c_width: 150
n_blocks: 6

# optimizer arguments
optimizer: Adam
epochs: 400
warmup_epochs: 10
lr: 0.0005
lr_scheduler: CosineAnnealingLRWithWarmup  # PolynomialLRWithWarmup, CosineAnnealingLRWithWarmup
weight_decay: 0
clip_grad_norm: 1.0
fp16: False
shrink_outputs: 0.

# model-specific arguments
model: HMR
device: -1