
# logging
run_name: default
out_dir: ../../data/MasifLigand/outdir
test_freq: 
seed: 2023
auto_resume: 
mute_tqdm: False

# data args
data_dir: ../../data/MasifLigand/dataset_MasifLigand/
processed_dir: ../../data/MasifLigand/cache_npz
operator_dir: ../../data/MasifLigand/cache_operator
train_split_file: splits/train-list.txt
valid_split_file: splits/val-list.txt
test_split_file: splits/test-list.txt
use_chem_feat: True
use_geom_feat: True

# loader args
batch_size: 
num_data_workers: 
num_gdf: 

# model args
c_width: 150
n_blocks: 6

# optimizer arguments
optimizer: Adam
epoch: 400
warmup_epoch: 30
lr: 1e-4
lr_scheduler: constant  # PolynomialLRWithWarmup, CosineAnnealingLRWithWarmup
weight_decay: 0
clip_grad_norm: 1.0
fp16: False

# model-specific arguments
model: HMR
device: cuda:0