epochs: 100
device: 0
seed: 2023
log_dir: "./logs"

dataset:
  data_dir: "../data/MSP/"
  recompute: False

loader:
  batch_size_train: 1
  batch_size_val: 1
  num_workers: 6

model:
  in_channels: 5
  out_channel: 64
  C_width: 96
  N_block: 3
  drate: 0.3
  batch_norm: False