run_name: "NA"
epochs: 100
device: 2
seed: 2023
log_dir: "./"

dataset:
  data_dir: "../../data/MSP/"
  recompute: False

loader:
  batch_size_train: 1
  batch_size_val: 1
  num_workers: 6
  pin_memory: False
  prefetch_factor: 2

model:
  in_channels: 5
  out_channel: 64
  C_width: 96
  N_block: 3
  drate: 0.3
  batch_norm: False
  use_max: True
  use_mean: False
  use_xyz: False
  pos_weight: 4
  use_graph: True
  use_graph_only: False

optimizer:
  lr: 1e-4
  patience: 100
  factor: 0.5

train:
  save_top_k: 2
  early_stoping_patience: 10
  accumulate_grad_batches: 8
  val_check_interval: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  overfit_batches: 0.0
  gradient_clip_val: 1.0
  deterministic: False


hydra:
  run:
    dir: ../outputs/msp/
